import {
  Add,
  // AssignmentTurnedIn,
  Cancel,
  CarRental,
  Category,
  ContactMail,
  // Create,
  Dashboard,
  DirectionsCar,
  Done,
  FeaturedPlayList,
  // HomeRepairService,
  LocalActivity,
  Money,
  // LocalActivity,
  Notifications,
  Paid,
  People,
  PeopleAlt,
  Person,
  PersonAdd,
  // PersonAdd,
  Redeem,
  Reviews,
  Schedule,
  Star,
  Summarize,
  Support,
  ToggleOn,
  TwoWheeler,
  // TheaterComedy,
  VpnKey,
} from "@mui/icons-material";

const MenuItems = [
  {
    key: "1",
    title: "Dashboard",
    icon: <Dashboard className="iconColor" />,
    route: "/dashboard",
  },
  // {
  //   key: "2",
  //   title: "Manage Artists",
  //   icon: <AttractionsTwoTone className="iconColor" />,
  //   route: "/manage-artists",
  // },
  // {
  //   key: "11",
  //   title: "Manage  Managers",
  //   icon: <SupervisedUserCircleOutlined className="iconColor" />,
  //   route: "/manage-managers",
  // },

  {
    key: "3",
    icon: <People className="iconColor" />,
    title: "Riders",
    route: "/riders",
  },
  // {
  //   key: "14",
  //   icon: <PersonAdd className="iconColor" />,
  //   title: "Manage Requests",
  //   route: "/manage-requests",
  // },
  {
    key: "4",
    icon: <DirectionsCar className="iconColor" />,
    title: "Drivers",
    route: "drivers",
    submenus: [
      {
        key: "2",
        title: "All Drivers",
        icon: <PeopleAlt sx={{ color: "snow" }} />,
        route: "/drivers/all-drivers",
      },
      {
        key: "1",
        title: "Add New Driver",
        icon: <Add className="iconColor" sx={{ color: "#000" }} />,
        route: "/drivers/add-new-driver",
      },
      {
        key: "3",
        title: "Driver Payment",
        icon: <Money className="iconColor" sx={{ color: "#000" }} />,
        route: "/drivers/driver-payment",
      },
      {
        key: "4",
        title: "Requests",
        icon: <PersonAdd className="iconColor" sx={{ color: "#000" }} />,
        route: "/drivers/add-new-driver",
      },
    ],
  },
  {
    key: "2",
    icon: <TwoWheeler className="iconColor" />,
    title: "Rides",
    route: "/rides",
    submenus: [
      {
        key: "1",
        title: "Active Rides",
        icon: <ToggleOn className="iconColor" sx={{ color: "#000" }} />,
        route: "/rides/active-rides",
      },
      {
        key: "2",
        title: "Completed Rides",
        icon: <Done className="iconColor" sx={{ color: "#000" }} />,
        route: "/rides/completed-rides",
      },
      {
        key: "3",
        title: "Scheduled Rides",
        icon: <Schedule className="iconColor" sx={{ color: "#000" }} />,
        route: "/rides/scheduled-rides",
      },
      {
        key: "4",
        title: "Rental Rides",
        icon: <CarRental className="iconColor" sx={{ color: "#000" }} />,
        route: "/rides/rental-rides",
      },
      {
        key: "5",
        title: "Cancelled Rides",
        icon: <Cancel className="iconColor" sx={{ color: "#000" }} />,
        route: "/rides/cancelled-rides",
      },
    ],
  },
  {
    key: "11",
    icon: <Category className="iconColor" />,
    title: "Vehicles",
    route: "/vehicles",
  },
  // {
  //   key: "20",
  //   icon: <Category className="iconColor" />,
  //   title: "Categories",
  //   route: "/categories",
  // },
  // {
  //   key: "12",
  //   icon: <TheaterComedy className="iconColor" />,
  //   title: "Manage Genres",
  //   route: "/manage-genres",
  // },
  {
    key: "13",
    icon: <LocalActivity className="iconColor" />,
    title: "Localization",
    route: "/localization",
  },

  {
    key: "7",
    icon: <Redeem className="iconColor" />,
    title: "Coupons",
    route: "/coupons",
  },
  {
    key: "19",
    icon: <FeaturedPlayList className="iconColor" />,
    title: "Features",
    route: "/features",
  },
  {
    key: "5",
    icon: <Person className="iconColor" />,
    title: "Operators",
    route: "/operators",
    submenus: [
      {
        key: "1",
        title: "View Operators",
        icon: <Person className="iconColor" sx={{ color: "#000" }} />,
        route: "/operators/view-operators",
      },
      {
        key: "2",
        title: "Requests",
        icon: <PersonAdd className="iconColor" sx={{ color: "#000" }} />,
        route: "/operators/requests",
      },
    ],
  },
  {
    key: "16",
    icon: <Money className="iconColor" />,
    title: "Pricing",
    route: "/pricing",
  },

  {
    key: "17",
    icon: <Summarize className="iconColor" />,
    title: "Statement",
    route: "/statements",
  },
  {
    key: "18",
    icon: <Paid className="iconColor" />,
    title: "Earning Reports",
    route: "/earning-report",
    submenus: [
      {
        key: "1",
        title: "Driver Payment",
        icon: <Money className="iconColor" sx={{ color: "#000" }} />,
        route: "/driver-payment",
      },
      {
        key: "2",
        title: "Operator Payment",
        icon: <Money className="iconColor" sx={{ color: "#000" }} />,
        route: "/operator-payment",
      },
    ],
  },
  {
    key: "8",
    icon: <Support className="iconColor" />,
    title: "Faqs",
    route: "/supports",
  },
  {
    key: "6",
    icon: <Reviews className="iconColor" />,
    title: "Reviews & Ratings",
    route: "/manage-reviews",
    submenus: [
      {
        key: "1",
        title: "Rider Ratings",
        icon: <Star className="iconColor" sx={{ color: "#000" }} />,
        route: "/rider-ratings",
      },
      {
        key: "2",
        title: "Driver Ratings",
        icon: <Star className="iconColor" sx={{ color: "#000" }} />,
        route: "driver-ratings",
      },
    ],
  },
  {
    key: "21",
    icon: <ContactMail className="iconColor" />,
    title: "Contacts",
    route: "/contacts",
  },
  {
    key: "9",
    icon: <Notifications className="iconColor" />,
    title: "Notifications",
    route: "/notifications",
  },
  {
    key: "10",
    icon: <VpnKey className="iconColor" />,
    title: "Change Password",
    route: "/change-password",
  },
];

export default MenuItems;
